export const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST"
export const ALL_PRODUCT_SUCESS = "ALL_PRODUCT_SUCESS"
export const ALL_PRODUCT_FAIL = "ALL_PRODUCT_FAIL"
export const CLEAR_ERRORS = "CLEAR_ERRORS"