export const ALL_LOGIN_REQUEST = "ALL_LOGIN_REQUEST"
export const ALL_LOGIN_SUCESS = "ALL_LOGIN_SUCESS"
export const ALL_LOGIN_FAIL = "ALL_LOGIN_FAIL"

export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";


export const CLEAR_ERRORS = "CLEAR_ERRORS"
